name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull data with DVC
      run: |
        dvc pull

    - name: Train model
      run: |
        python train.py --data-path data/winequality-red.csv --model-dir model --log-dir logs

    - name: Push data with DVC
      run: |
        dvc push

    - name: Commit and push model
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add model/best_model.joblib logs/training.log
        git commit -m "Update trained model and logs"
        git push

  build:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/wine_quality:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/wine_quality:latest
        docker run -d -p 5000:5000 --name wine_quality_app ${{ secrets.DOCKER_USERNAME }}/wine_quality:latest
